name: Vilicus
version: 0.3.0
main: de.marmeladenoma.vilicus_spigot.VilicusPlugin
description:
  Modern moderation and community management toolset featuring
  player activity tracking, penalties and chat support
api-version: 1.16
commands:
  reason:
  punish:
  unpunish:
  support:
  report: